---
title: "Untitled"
author: "Kate Tran"
date: "7/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readr)
```

```{r}
data_wide <- read_csv("../outputs/asthma_inflammation_wide.csv")
```

```{r}
# Create ever variables
data_wide$asthma_diagnosis_l_ever <- apply(data_wide[,grepl("asthma_diagnosis_l", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$asthma_diagnosis_l_ever <- ifelse( (is.na(data_wide$asthma_diagnosis_l_ever) & 
                                                     (apply(data_wide[,which(grepl("asthma_diagnosis_l", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$asthma_diagnosis_l_ever)

data_wide$asthma_attack_l_ever <- apply(data_wide[,grepl("asthma_attack_l", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$asthma_attack_l_ever <- ifelse( (is.na(data_wide$asthma_attack_l_ever) & 
                                                     (apply(data_wide[,which(grepl("asthma_attack_l", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$asthma_attack_l_ever)

data_wide$asthma_composite_ever <- apply(data_wide[,grepl("asthma_composite", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$asthma_composite_ever <- ifelse( (is.na(data_wide$asthma_composite_ever) & 
                                                     (apply(data_wide[,which(grepl("asthma_composite", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$asthma_composite_ever)

data_wide$recent_active_asthma_ever <- apply(data_wide[,grepl("recent_active_asthma", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$recent_active_asthma_ever <- ifelse( (is.na(data_wide$recent_active_asthma_ever) & 
                                                     (apply(data_wide[,which(grepl("recent_active_asthma", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$recent_active_asthma_ever)

data_wide$Montelukast_2w_ever <- apply(data_wide[,grepl("Montelukast_2w__", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$Montelukast_2w_ever <- ifelse( (is.na(data_wide$Montelukast_2w_ever) & 
                                                     (apply(data_wide[,which(grepl("Montelukast_2w__", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$Montelukast_2w_ever)

data_wide$Immune_modulators_2w_ever <- apply(data_wide[,grepl("Immune_modulators_2w__", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$Immune_modulators_2w_ever <- ifelse( (is.na(data_wide$Immune_modulators_2w_ever) & 
                                                     (apply(data_wide[,which(grepl("Immune_modulators_2w__", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$Immune_modulators_2w_ever)

data_wide$Systemic_steroids_class_H02_2w_ever <- apply(data_wide[,grepl("Systemic_steroids_class_H02_2w__", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$Systemic_steroids_class_H02_2w_ever <- ifelse( (is.na(data_wide$Systemic_steroids_class_H02_2w_ever) & 
                                                     (apply(data_wide[,which(grepl("Systemic_steroids_class_H02_2w__", colnames(data_wide)))], 1, 
                                                            function(x) {any(x == 0)}))), 
                                                  0, data_wide$Systemic_steroids_class_H02_2w_ever)

data_wide$Topical_steroids_2w_ever <- apply(data_wide[,grepl("Topical_steroids_2w__", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$Topical_steroids_2w_ever <- ifelse( (is.na(data_wide$Topical_steroids_2w_ever) & 
                                                     (apply(data_wide[,which(grepl("Topical_steroids_2w__", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$Topical_steroids_2w_ever)

data_wide$medhx_6a_l_ever <- apply(data_wide[,grepl("medhx_6a_l__", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})
data_wide$medhx_6a_l_ever <- ifelse( (is.na(data_wide$medhx_6a_l_ever) & 
                                                     (apply(data_wide[,which(grepl("medhx_6a_l__", colnames(data_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, data_wide$medhx_6a_l_ever)

data_wide$medhx_ss_6l_times_p_l_ever <- apply(data_wide[,grepl("medhx_ss_6l_times_p_l", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})


data_wide$SA_y_ever <- apply(data_wide[,grepl("SA_y", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})

data_wide$SI_y_ever <- apply(data_wide[,grepl("SI_y", colnames(data_wide))],1 ,function(x) {any(x == 1)*1})

data_wide$CBCL_mean <- rowMeans(data_wide[,which(grepl("cbcl_scr_syn_totprob_r", colnames(data_wide)))], na.rm = T)

data_wide$BPM_mean <- rowMeans(data_wide[,which(grepl("bpm_y_scr_totalprob_r", colnames(data_wide)))], na.rm = T)

data_wide$asthma_num_attack_mean <- rowMeans(data_wide[,which(grepl("medhx_ss_6l_times_p_l__", colnames(data_wide)))], na.rm = T)
data_wide$asthma_num_attack_sum <- rowSums(data_wide[,which(grepl("medhx_ss_6l_times_p_l__", colnames(data_wide)))], na.rm = T)

data_wide$Asthma_medications_2w_total_mean <- rowMeans(data_wide[,which(grepl("Asthma_medications_2w_total__", colnames(data_wide)))], na.rm = T)
data_wide$Asthma_medications_2w_total_sum <- rowSums(data_wide[,which(grepl("Asthma_medications_2w_total__", colnames(data_wide)))], na.rm = T)

data_wide$age_2y_years <- data_wide$age__2y/12
```

```{r}
write.csv(file = "../outputs/data_wide_mm.csv", x = data_wide, row.names = F, na = "")
```

