---
title: "Untitled"
author: "Kate Tran"
date: "4/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readr)
library(tidyr)
library(data.table)
library(psych)
library(tidyr)

source("../config.R")
```

# Read data

```{r}
# Combine demographics at baseline and longitudinal
demographics_baseline <- read.csv("../outputs/demographics_baseline.csv")
demographics_long <- read.csv("../outputs/demographics_long.csv")

demo_race = demographics_baseline[,grep("src|race|hisp", colnames(demographics_baseline))]

demographics_long = merge(demographics_long, demo_race)
demographics_long = demographics_long[demographics_long$eventname != "baseline_year_1_arm_1",]
demo_merge = bind_rows(demographics_baseline, demographics_long)
```

```{r}
# Exposome
exposome_baseline <- read_csv("../outputs/exposome_baseline.csv") %>% dplyr::select(-contains(c("interview", "sex", "eventname")))
geo_data_baseline <- read_csv("../outputs/geo_data_baseline.csv") %>% 
  filter(eventname == "baseline_year_1_arm_1") %>% dplyr::select(-contains(c("interview", "sex", "eventname")))

# Physical health
asthma_inflammation_ph <- read_csv("../outputs/asthma_inflammation_ph_notcarry.csv")
physicalhealth_sum <- read_csv("../outputs/physicalhealth_sum.csv") 

# Site
site <- read_csv("../outputs/site.csv") %>% dplyr::select(src_subject_id, eventname, site_id_l_br)

# Medications 
medications <- read_csv("../outputs/medications.csv", col_types = cols(.default = "n", "src_subject_id" = "c", "eventname" = "c", "sex" = "c")) 

# Genetics
genetic <- read_csv(paste0(genetic_files_path, "genetic.csv"))

# Suicide
suicide_long <- read_csv("../outputs/suicide_long.csv") 

# CBCL and BPM
psychopathology_sum_scores <- read_csv("../outputs/psychopathology_sum_scores.csv") 
```

# Merge data
```{r}
asthma_inflammation_set <- asthma_inflammation_ph %>%
  full_join(medications) %>% 
  left_join(demo_merge) %>% 
  left_join(suicide_long) %>% 
  left_join(exposome_baseline) %>% 
  left_join(psychopathology_sum_scores) %>% 
  left_join(geo_data_baseline) %>% 
  left_join(physicalhealth_sum) %>% 
  left_join(genetic) %>% 
  left_join(site)

# Create the asthma composite feature
asthma_inflammation_set$asthma_composite = apply(asthma_inflammation_set[,c("Asthma_medications_2w","asthma_diagnosis_l","asthma_attack_l")], 1, function(r) any(r==1)*1)

# Recent active asthma
asthma_inflammation_set$recent_active_asthma = apply(asthma_inflammation_set[,c("asthma_diagnosis_l","asthma_attack_l")], 1, function(r) any(r==1)*1)

asthma_inflammation_set <- asthma_inflammation_set %>% 
  filter(eventname != "3_year_follow_up_y_arm_1") %>%
  mutate(timepoint = case_when(eventname == "baseline_year_1_arm_1" ~ 1,
                               eventname == "1_year_follow_up_y_arm_1" ~ 2,
                               eventname == "2_year_follow_up_y_arm_1" ~ 3,
                               TRUE ~ NA_real_))
  

# Remove empty columns
asthma_inflammation_set <- asthma_inflammation_set %>% 
  dplyr::select_if(., function(x) any(!is.na(x)))

write.csv(file = "../outputs/asthma_inflammation_set.csv", x = asthma_inflammation_set, row.names = F, na = "")
```

# Wide data
```{r}
asthma_inflammation_wide <- asthma_inflammation_set %>%
  dplyr::select(age, contains(c("src", "eventname", "sex", "race", "hisp", "devhx_3_p", "rel_family_id", "reshist",
                                "asthma_PRS", "genetic_afr", "site_id_l_br", "parents_avg_edu", "household_income",
                                "asthma_diagnosis", "asthma_attack_l", "asthma_composite", "recent_active_asthma", 
                                "Montelukast", "Immune_modulators", "steroids", "SA_y", "SI_y", "cbcl", "bpm",
                                "medhx_ss_6l_times_p_l", "Asthma_medications_2w_total", "medhx_6a_l", "Asthma_medications_2w"))) %>% 
  mutate(eventname = recode(eventname,
                            baseline_year_1_arm_1 = "baseline",
                            `1_year_follow_up_y_arm_1` = "1y",
                            `2_year_follow_up_y_arm_1` = "2y")) %>%
  pivot_wider(., names_from = eventname, 
              values_from = c(age, site_id_l_br:Asthma_medications_2w),
                              names_sep = "__") %>%
  janitor::remove_empty(., which = c("rows", "cols"), quiet = TRUE) %>%
  # rename variables to use later
  rename(
    # use site id at 1-year
    site_id_l_br = "site_id_l_br__1y",
    # use parent education at 1y
    parents_avg_edu = "parents_avg_edu__1y",
    # use household income at 2y
    household_income = "household_income__2y"
  )

write.csv(file = "../outputs/asthma_inflammation_wide.csv", x = asthma_inflammation_wide, row.names = F, na = "")
```













